name: AntiAutoFish
main: Limbo.Main
author: Limbo48
version: 1.07
api-version: 1.15

commands:
  afreload:
    description: Reload config
    aliases: [arl, afrl]
    permission: af.admin

permissions:
  af.admin:
    default: op
    children:
      af.bypass: true
  af.bypass:
    default: op